package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.Ctrl;

public interface CtrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insert(Ctrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insertSelective(Ctrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    Ctrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKeySelective(Ctrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ctrl
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKey(Ctrl record);
}