package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKey(Department record);
}