package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.MenuGroup;

public interface MenuGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insert(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int insertSelective(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    MenuGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKeySelective(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_group
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    int updateByPrimaryKey(MenuGroup record);
}