package com.startcaft.ssm.po;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.depart_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String departDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.depart_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.application_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.id
     *
     * @return the value of tb_department.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.id
     *
     * @param id the value for tb_department.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.depart_desc
     *
     * @return the value of tb_department.depart_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getDepartDesc() {
        return departDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.depart_desc
     *
     * @param departDesc the value for tb_department.depart_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setDepartDesc(String departDesc) {
        this.departDesc = departDesc == null ? null : departDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.is_enable
     *
     * @return the value of tb_department.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.is_enable
     *
     * @param isEnable the value for tb_department.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.depart_name
     *
     * @return the value of tb_department.depart_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.depart_name
     *
     * @param departName the value for tb_department.depart_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.application_id
     *
     * @return the value of tb_department.application_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.application_id
     *
     * @param applicationId the value for tb_department.application_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.parent_id
     *
     * @return the value of tb_department.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.parent_id
     *
     * @param parentId the value for tb_department.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}