package com.startcaft.ssm.po;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String groupDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.is_enbale
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Boolean isEnbale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.id
     *
     * @return the value of tb_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.id
     *
     * @param id the value for tb_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_desc
     *
     * @return the value of tb_group.group_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_desc
     *
     * @param groupDesc the value for tb_group.group_desc
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc == null ? null : groupDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.is_enbale
     *
     * @return the value of tb_group.is_enbale
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Boolean getIsEnbale() {
        return isEnbale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.is_enbale
     *
     * @param isEnbale the value for tb_group.is_enbale
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setIsEnbale(Boolean isEnbale) {
        this.isEnbale = isEnbale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_name
     *
     * @return the value of tb_group.group_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_name
     *
     * @param groupName the value for tb_group.group_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }
}