package com.startcaft.ssm.po;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.icon
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.sort_index
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_url
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.id
     *
     * @return the value of tb_menu.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.id
     *
     * @param id the value for tb_menu.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.is_enable
     *
     * @return the value of tb_menu.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.is_enable
     *
     * @param isEnable the value for tb_menu.is_enable
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.icon
     *
     * @return the value of tb_menu.icon
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.icon
     *
     * @param icon the value for tb_menu.icon
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_name
     *
     * @return the value of tb_menu.menu_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_name
     *
     * @param menuName the value for tb_menu.menu_name
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.sort_index
     *
     * @return the value of tb_menu.sort_index
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.sort_index
     *
     * @param sortIndex the value for tb_menu.sort_index
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_url
     *
     * @return the value of tb_menu.menu_url
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_url
     *
     * @param menuUrl the value for tb_menu.menu_url
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.parent_id
     *
     * @return the value of tb_menu.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.parent_id
     *
     * @param parentId the value for tb_menu.parent_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}