package com.startcaft.ssm.po;

public class UserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_group.user_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_group.group_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_group.id
     *
     * @return the value of tb_user_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_group.id
     *
     * @param id the value for tb_user_group.id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_group.user_id
     *
     * @return the value of tb_user_group.user_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_group.user_id
     *
     * @param userId the value for tb_user_group.user_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_group.group_id
     *
     * @return the value of tb_user_group.group_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_group.group_id
     *
     * @param groupId the value for tb_user_group.group_id
     *
     * @mbggenerated Thu Oct 08 17:27:14 CST 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}